const express = require("express");
const router = express.Router();
const { getGoals, getGoalById, createGoal, updateGoal, deleteGoal } = require("./goals_controllers");
const { validate } = require("../../middleware/auth_middleware");
router.get('/', validate, getGoals);
router.get('/:id', validate, getGoalById);
router.post('/', validate, createGoal);
router.put('/:id', validate, updateGoal);
router.delete('/:id', validate, deleteGoal);
module.exports = router;
